-- create DATABASE security_test_db;

create table person(
    id int primary key generated by default as identity,
    username varchar(100),
    year_of_birth int,
    password varchar,
    role varchar(100)
);

insert into person(username, year_of_birth, password, role)
values ('roma', 2001, 'roma', 'ROLE_USER');
insert into person(username, year_of_birth, password, role)
values ('anna', 2003, 'anna', 'ROLE_USER');
insert into person(username, year_of_birth, password, role)
values ('nastya', 2005, 'nastya', 'ROLE_USER');

